# Generated by Django 5.2.4 on 2025-07-21 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
    ]
