# Generated by Django 5.2.4 on 2025-07-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
