# Generated by Django 5.2.4 on 2025-07-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_video_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': 'created_at'},
        ),
    ]
